[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.11.11
    knolleary/PubSubClient
    milesburton/DallasTemperature

build_flags = 
    -D WIFI_SSID=\"your-ssid\"
    -D WIFI_PASSWORD=\"your-password\"
    -D MQTT_HOST=\"broker.hivemq.com\"
    -D MQTT_PORT=1883
    -D MQTT_TEAM=\"team-quad-core\"
    -D MQTT_DEVICE=\"river-node-01\"